# docker-compose.yml
version: '3'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: never
  php:
    image: php:5.6-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
  # NEW IN THIS SECTION!!!
  phpunit:
    image: php:5.6-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit